### ISSUE TITLE
Newbie homer intallation

### ISSUE THREAD

**Issue by djafarsidik** [Homer-Conferencing/Homer-Conferencing#53]
Hi all..
My name is Diky i am from Indonesia, i would like to ask about homer installation, is there any special thing should i prepared on my PC linux or windows (currently i use Ubuntu 12.04) to make Homer working ?
I have downloaded homer from web, i took linux 32 version .. and i extracted tar bz file to some place, i only saw start and homer files which i can execute.. so i tried to use both files..homer displayed but why my camera didn't work ? eventhough it has been detected, homer only displayed "waiting for data".

Same thing happen in windows, i tried it in XP used both installer and zip version, but camera still not working and also i got some error which tell somehthing about "JIT debugger error "..the only thing i can do with homer untill now is chatting between pc. I have tried to find tutorial in homer's website, but i could not find what i need.. i appreciate your best support, and i'm sorry for my poor english.

**Comment by ThomasVolkert** [comment]
@djafarsidik: If you face any additional problems with the installtion, please, ask here again and we re-open the issue again. 
Best regards.
