### ISSUE TITLE
Automatic Login at startup

### ISSUE THREAD

**Issue by FreddyFelix** [Homer-Conferencing/Homer-Conferencing#55]
I just already try your program, homer conferencing. That is a good
program.
But I want ask, how to set that program automatic run and login (with password keeper if I don't sign out before) when startup windows and automatic minimize like yahoo messenger or skype.
It is better if after startup windows, the program standby at notification area.
Thanks.

**Comment by ThomasVolkert** [comment]
At the moment this function is missing. But maybe you (or someone else) wants to contribute by a patch for this? In this case feel free and create a pull request.
