### ISSUE TITLE
-

### ISSUE THREAD

**Issue by technop** [Homer-Conferencing/Homer-Conferencing#65]
--

**Comment by ThomasVolkert** [comment]
Some years ago I had the same problem in another project, I searched the Internet for a solution - but I can't remember how I solved it. (But this error is not caused by the build system.)

**Comment by technop** [comment]
Try again

**Comment by technop** [comment]
I cant find the real file that is included...
DbgHelp.h
DbgHelp.h:120:5: error: '_Out_writes_' has not been declared

how can i found this file on the net?
how can i download directly the real header file?
Help me please sir

**Comment by technop** [comment]
No help

**Comment by ThomasVolkert** [comment]
Please, do not delete your former messages but leave them as possible help for future questions from other users. Thank you.

Regarding the problem of this issue thread I do not have an offhanded solution.

Regarding the dbghelp.h problem there were several possible solutions in the other issue. The dbghelp.h file is from Microsoft and included in several official packages from the company. Search for the file version which includes the needed function and include it via the CMakeLists.txt (as explained in the former thread).

**Comment by technop** [comment]
Okay
Solved by editing make file

**Comment by technop** [comment]
[ 30%] Building CXX object Homer/bin/CMakeFiles/Homer.dir/__/src/HomerApplication.cpp.obj
In file included from e:/IDE/Qt/Qt5.4.1.1-/5.4/mingw491_32/include/QtGui/qtextedit.h:1:0,
                 from e:/IDE/Qt/Qt5.4.1.1-/5.4/mingw491_32/src/gui/widgets/qtextbrowser.h:45,
                 from e:/IDE/Qt/Qt5.4.1.1-/5.4/mingw491_32/include/QtGui/qtextbrowser.h:1,
                 from e:/IDE/Qt/Qt5.4.1.1-/5.4/mingw491_32/include/QtGui/QTextBrowser:1,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/Widgets/MessageHistory.h:30,
                 from C:/msys/1.0/home/user1/HomerBuild/Build/Debug/Homer/bin/ui_MessageWidget.h:26,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/Widgets/MessageWidget.h:36,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/Widgets/ParticipantWidget.h:30,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/Widgets/StreamingControlWidget.h:33,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/MainWindow.h:36,
                 from C:/msys/1.0/home/user1/Homer/bin/../include/HomerApplication.h:30,
                 from c:/msys/1.0/home/user1/Homer/src/HomerApplication.cpp:28:
e:/IDE/Qt/Qt5.4.1.1-/5.4/mingw491_32/src/gui/widgets/qtextedit.h:235:16: error: 'QPrinter' has not been declared
     void print(QPrinter *printer) const;
                ^
make[3]: *** [Homer/bin/CMakeFiles/Homer.dir/__/src/HomerApplication.cpp.obj] Error 1
make[2]: *** [Homer/bin/CMakeFiles/Homer.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [debug] Error 2

**Comment by technop** [comment]
Last error solved by replacing qtextedit.h file by other src...
new:

[ 32%] Building CXX object Homer/bin/CMakeFiles/Homer.dir/__/src/Dialogs/ConfigurationDialog.cpp.obj
In file included from C:/msys/1.0/home/user1/Homer/bin/../include/Dialogs/ConfigurationDialog.h:31:0,
                 from c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:27:
C:/msys/1.0/home/user1/HomerBuild/Build/Debug/Homer/bin/ui_ConfigurationDialog.h: In member function 'void Ui_ConfigurationDialog:
:setupUi(QDialog*)':
C:/msys/1.0/home/user1/HomerBuild/Build/Debug/Homer/bin/ui_ConfigurationDialog.h:360:10: note: variable tracking size limit exceed
ed with -fvar-tracking-assignments, retrying without
     void setupUi(QDialog *ConfigurationDialog)

**Comment by technop** [comment]
CMakeFiles/Homer.dir/objects.a(moc_StreamingControlWidget.cpp.obj):moc_StreamingControlWidget.cpp:(.rdata$_ZTVN5Homer3Gui22Streami
ngControlWidgetE[__ZTVN5Homer3Gui22StreamingControlWidgetE]+0xd0): undefined reference to `QWidget::fontChange(QFont const&)'
CMakeFiles/Homer.dir/objects.a(moc_StreamingControlWidget.cpp.obj):moc_StreamingControlWidget.cpp:(.rdata$_ZTVN5Homer3Gui22Streami
ngControlWidgetE[__ZTVN5Homer3Gui22StreamingControlWidgetE]+0xd4): undefined reference to `QWidget::windowActivationChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_StreamingControlWidget.cpp.obj):moc_StreamingControlWidget.cpp:(.rdata$_ZTVN5Homer3Gui22Streami
ngControlWidgetE[__ZTVN5Homer3Gui22StreamingControlWidgetE]+0xd8): undefined reference to `QWidget::languageChange()'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xc4): undefined reference to `QWidget::styleChange(QStyle&)'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xc8): undefined reference to `QWidget::enabledChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xcc): undefined reference to `QWidget::paletteChange(QPalette const&)'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xd0): undefined reference to `QWidget::fontChange(QFont const&)'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xd4): undefined reference to `QWidget::windowActivationChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_VideoWidget.cpp.obj):moc_VideoWidget.cpp:(.rdata$_ZTVN5Homer3Gui11VideoWidgetE[__ZTVN5Homer3Gui
11VideoWidgetE]+0xd8): undefined reference to `QWidget::languageChange()'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [C:/msys/1.0/home/user1/HomerBuild/bin/Homer.exe] Error 1
make[2]: *** [Homer/bin/CMakeFiles/Homer.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [debug] Error 2

**Comment by technop** [comment]
[ 28%] Built target HomerConference
Linking CXX executable /C/msys/1.0/home/user1/HomerBuild/bin/Homer.exe
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog38LetUserSelectStunServ
erFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:780: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog37LetUserSelectSipServe
rFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:828: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(AudioWidget.cpp.obj): In function `ZN5Homer3Gui11AudioWidget13StartRecorderEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/AudioWidget.cpp:491: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK7
QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget12RenameDialogEv'
:
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:1550: undefined reference to `_imp___ZN12QInputDialog7getTextE
P7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget21AddPlaylistUrls
DialogEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:579: undefined reference to `_imp___ZN12QInputDialog7getTextEP
7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ParticipantWidget.cpp.obj): In function `ZN5Homer3Gui17ParticipantWidget21ActionRecordMovieFileEv':

c:/msys/1.0/home/user1/Homer/src/Widgets/ParticipantWidget.cpp:1980: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWi
dgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget14ShowFullScreenERiS2_':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1369: undefined reference to `_imp___ZNK7QWidget5mapToEPS_RK6QPoint'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget13StartRecorderEb':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1573: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK
7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc4): undefined reference to `QWidget::styleChange(QStyle&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc8): undefined reference to `QWidget::enabledChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xcc): undefined reference to `QWidget::paletteChange(QPalette const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd0): undefined reference to `QWidget::fontChange(QFont const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd4): undefined reference to `QWidget::windowActivationChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd8): undefined reference to `QWidget::languageChange()'

**Comment by technop** [comment]
[ 28%] Built target HomerConference
Linking CXX executable /C/msys/1.0/home/user1/HomerBuild/bin/Homer.exe
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog38LetUserSelectStunServ
erFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:780: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog37LetUserSelectSipServe
rFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:828: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(AudioWidget.cpp.obj): In function `ZN5Homer3Gui11AudioWidget13StartRecorderEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/AudioWidget.cpp:491: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK7
QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget12RenameDialogEv'
:
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:1550: undefined reference to `_imp___ZN12QInputDialog7getTextE
P7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget21AddPlaylistUrls
DialogEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:579: undefined reference to `_imp___ZN12QInputDialog7getTextEP
7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ParticipantWidget.cpp.obj): In function `ZN5Homer3Gui17ParticipantWidget21ActionRecordMovieFileEv':

c:/msys/1.0/home/user1/Homer/src/Widgets/ParticipantWidget.cpp:1980: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWi
dgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget14ShowFullScreenERiS2_':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1369: undefined reference to `_imp___ZNK7QWidget5mapToEPS_RK6QPoint'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget13StartRecorderEb':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1573: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK
7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc4): undefined reference to `QWidget::styleChange(QStyle&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc8): undefined reference to `QWidget::enabledChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xcc): undefined reference to `QWidget::paletteChange(QPalette const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd0): undefined reference to `QWidget::fontChange(QFont const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd4): undefined reference to `QWidget::windowActivationChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd8): undefined reference to `QWidget::languageChange()'

**Comment by technop** [comment]
[ 28%] Built target HomerConference
Linking CXX executable /C/msys/1.0/home/user1/HomerBuild/bin/Homer.exe
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog38LetUserSelectStunServ
erFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:780: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog37LetUserSelectSipServe
rFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:828: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(AudioWidget.cpp.obj): In function `ZN5Homer3Gui11AudioWidget13StartRecorderEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/AudioWidget.cpp:491: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK7
QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget12RenameDialogEv'
:
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:1550: undefined reference to `_imp___ZN12QInputDialog7getTextE
P7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget21AddPlaylistUrls
DialogEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:579: undefined reference to `_imp___ZN12QInputDialog7getTextEP
7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ParticipantWidget.cpp.obj): In function `ZN5Homer3Gui17ParticipantWidget21ActionRecordMovieFileEv':

c:/msys/1.0/home/user1/Homer/src/Widgets/ParticipantWidget.cpp:1980: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWi
dgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget14ShowFullScreenERiS2_':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1369: undefined reference to `_imp___ZNK7QWidget5mapToEPS_RK6QPoint'
CMakeFiles/Homer.dir/objects.a(VideoWidget.cpp.obj): In function `ZN5Homer3Gui11VideoWidget13StartRecorderEb':
c:/msys/1.0/home/user1/Homer/src/Widgets/VideoWidget.cpp:1573: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK
7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc4): undefined reference to `QWidget::styleChange(QStyle&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xc8): undefined reference to `QWidget::enabledChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xcc): undefined reference to `QWidget::paletteChange(QPalette const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd0): undefined reference to `QWidget::fontChange(QFont const&)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd4): undefined reference to `QWidget::windowActivationChange(bool)'
CMakeFiles/Homer.dir/objects.a(moc_MainWindow.cpp.obj):moc_MainWindow.cpp:(.rdata$_ZTVN5Homer3Gui10MainWindowE[__ZTVN5Homer3Gui10M
ainWindowE]+0xd8): undefined reference to `QWidget::languageChange()'

**Comment by technop** [comment]
[ 24%] Built target HomerMultimedia
[ 28%] Built target HomerConference
Linking CXX executable /C/msys/1.0/home/user1/HomerBuild/bin/Homer.exe
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog38LetUserSelectStunServ
erFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:780: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(ConfigurationDialog.cpp.obj): In function `ZN5Homer3Gui19ConfigurationDialog37LetUserSelectSipServe
rFromSuggestionsEv':
c:/msys/1.0/home/user1/Homer/src/Dialogs/ConfigurationDialog.cpp:828: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QW
idgetRK7QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(AudioWidget.cpp.obj): In function `ZN5Homer3Gui11AudioWidget13StartRecorderEv':
c:/msys/1.0/home/user1/Homer/src/Widgets/AudioWidget.cpp:491: undefined reference to `_imp___ZN12QInputDialog7getItemEP7QWidgetRK7
QStringS4_RK11QStringListibPb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget12RenameDialogEv'
:
c:/msys/1.0/home/user1/Homer/src/Widgets/OverviewPlaylistWidget.cpp:1550: undefined reference to `_imp___ZN12QInputDialog7getTextE
P7QWidgetRK7QStringS4_N9QLineEdit8EchoModeES4_Pb6QFlagsIN2Qt10WindowTypeEE'
CMakeFiles/Homer.dir/objects.a(OverviewPlaylistWidget.cpp.obj): In function `ZN5Homer3Gui22OverviewPlaylistWidget21AddPlaylistUrls

**Comment by technop** [comment]
After compiling is complete;
The Homer.exe is reporting some errors:
This application failed to start...
Because it could not find or load the Qt platform "windows"

**Comment by ThomasVolkert** [comment]
How have you solved the error "QCommandLineParser: argument list cannot be empty, it should contain at least the executable name" ?

**Comment by technop** [comment]
No

**Comment by technop** [comment]
Help me to make a good and complete installer package
This is not fully packaged on foo/bar folder as an installer full package
i am restarting all steps

**Comment by technop** [comment]
I want to help this project after my project...
