### ISSUE TITLE
ARM support 

### ISSUE THREAD

**Issue by gustavklopp** [Homer-Conferencing/Homer-Conferencing#68]
I'd like to use a pcDuino (it's an Arduino like computer with 1GB of RAM, a 1GHz ARM Cortex A8) as server with Homer-conferencing on it.

Do you think there's a way to do it?
Thanks for this wonderful project!
Regards

**Comment by ThomasVolkert** [comment]
Sure, this should be possible. Are you interested in contributing to the project with new ARM support?
BR,Thomas.

**Comment by gustavklopp** [comment]
I may be some help. I've got at least an ARM computer to test... (it's got a 12.04 Ubuntu (Linaro variant)). The hardware requirements would be meet for it? (1Gb of RAM and 1Gh Cortex A8. It's more powerful than an Arduino or Raspberry py but more like a netbook)

**Comment by ThomasVolkert** [comment]
That should be fine. If you have prepared some patches, send a pull request here on Github.
Thanks and BR,Thomas.
